name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test output
      run: echo "Hello World!"
    - name: Run tests
      run: xcodebuild -workspace Mintee.xcworkspace -scheme Mintee -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' test
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
