name: Run AUT and UIT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { scheme: 'iPhone-11-iOS-14.4', destination: 'platform=iOS Simulator,name=iPhone 11,OS=14.4' }
    steps:
    - uses: actions/checkout@v2
    - name: Update gems
      run: bundle install
    - name: Update pods
      run: pod install
    - name: Run functional AUT
      run: xcodebuild -workspace Mintee.xcworkspace -scheme Mintee -sdk iphonesimulator -destination '${{ matrix.run-config['destination'] }}' '-only-testing:Mintee_AUT_Function' test | bundle exec xcpretty --test --pretty
    - name: Run performance AUT
      run: xcodebuild -workspace Mintee.xcworkspace -scheme Mintee -sdk iphonesimulator -destination '${{ matrix.run-config['destination'] }}' '-only-testing:Mintee_AUT_Performance' test | bundle exec xcpretty --test --pretty
    - name: Run UIT
      run: xcodebuild -workspace Mintee.xcworkspace -scheme Mintee -sdk iphonesimulator -destination '${{ matrix.run-config['destination'] }}' '-only-testing:Mintee_UIT' test | bundle exec xcpretty --test --pretty