name: Run AUT and UIT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: macos-latest
    strategy:
      matrix:
        run-config:
          - { destination: 'platform=iOS Simulator,name=iPhone 11,OS=14.4' }
    steps:
    - uses: actions/checkout@v2
    - name: Update bundler
      run: gem install bundler:2.2.23
    - name: Install RubyGems
      run: bundle install
    - name: Install pods
      run: pod install
    - name: Run functional AUT
      run: xcodebuild -workspace Mintee.xcworkspace -scheme Mintee -sdk iphonesimulator -destination '${{ matrix.run-config['destination'] }}' '-only-testing:Mintee_AUT_Function' test | xcpretty --test --color --report html
    - name: Archive functional AUT artifacts
      uses: actions/upload-artifact@v2
      with:
          name: functional-AUT-report
          path: build/reports/tests.html
    # - name: Run performance AUT
    #   run: xcodebuild -workspace Mintee.xcworkspace -scheme Mintee -sdk iphonesimulator -destination '${{ matrix.run-config['destination'] }}' '-only-testing:Mintee_AUT_Performance' test | xcpretty --test --color --report html
    # - name: Archive performance AUT artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #       name: performance-AUT-report
    #       path: build/reports/tests.html
    # - name: Run UIT
    #   run: xcodebuild -workspace Mintee.xcworkspace -scheme Mintee -sdk iphonesimulator -destination '${{ matrix.run-config['destination'] }}' '-only-testing:Mintee_UIT' test | xcpretty --test --color --report html
    # - name: Archive UIT artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #       name: UIT-report
    #       path: build/reports/tests.html