name: Run AUT and UIT

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild -workspace Mintee.xcworkspace -scheme Mintee -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' test
